JobProject/urls.py
# urls.py

from django.contrib import admin
from django.urls import path , include
from apps.core.views import frontpage, signuppage


from apps.core.views import login_view, custom_logout
from . import views
from .views import ContactView


from django.urls import path




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', frontpage, name='frontpage'),
    path('signup/', signuppage, name='signup'),
    path('logout/', custom_logout, name='logout'),
    path('login/', login_view, name='login'),
    path('contact/', ContactView.as_view(), name='contact'),

    path('dashboard/', include('apps.userprofile.urls')),
    path('jobs/', include('apps.job.urls')),
    path('notifications/', include('apps.notification.urls')),
    path('social-auth/', include('social_django.urls'),name='social'),
    path('linkedin-auth/', views.linkedin_auth, name='linkedin_auth'),
    path('complete/linkedin-oauth2/', views.linkedin_callback, name='linkedin_callback'),


]

apps/job/urls.py
# urls.py

from django.urls import path
from .api import api_search

from .views import add_job,job_details,apply_for_job , search , edit_job
from apps.userprofile.views import refresh_linkedin_data


urlpatterns = [
    path('api/search/', api_search, name='api_search'),
    path('search/', search, name='search'),
    path('addjob/', add_job, name='addjob'),
    path('<int:pk>/',job_details , name='job_detail'),
    path('<int:job_id>/edit/', edit_job, name='edit_job'),

    path('<int:pk>/apply_for_job/', apply_for_job, name='apply_for_job'),
    path('refresh_linkedin_data/', refresh_linkedin_data, name='refresh_linkedin_data'),


]

apps/job/models.py
from django.contrib.auth.models import User
from django.db import models


class Job(models.Model):
    SIZE_1_9 = 'size_1-9'
    SIZE_10_49 = 'size_10-49'
    SIZE_50_99 = 'size_50-99'
    SIZE_100 = 'size_100'

    CHOICES_SIZE = (
        (SIZE_1_9, '1-9'),
        (SIZE_10_49, '10-49'),
        (SIZE_50_99, '50-99'),
        (SIZE_100, '100+'),
    )

    ACTIVE = 'active'
    EMPLOYED = 'employed'
    ARCHIVED = 'archived'

    CHOICES_STATUS = (
        (ACTIVE, 'Active'),
        (EMPLOYED, 'Employed'),
        (ARCHIVED, 'Archived')
    )

    title = models.CharField(max_length=255)
    short_description = models.TextField()
    long_description = models.TextField(blank=True, null=True)

    company_name = models.CharField(max_length=255 , default='Tylextech')
    company_address = models.CharField(max_length=255, blank=True, null=True)
    company_zipcode = models.CharField(max_length=255, blank=True, null=True)
    company_place = models.CharField(max_length=255, blank=True, null=True)
    company_country = models.CharField(max_length=255, blank=True, null=True)
    company_size = models.CharField(max_length=20, choices=CHOICES_SIZE, default=SIZE_1_9)

    created_by = models.ForeignKey(User, related_name='jobs', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    changed_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=ACTIVE)

    def __str__(self):
        return self.title

class Application(models.Model):
    job = models.ForeignKey(Job, related_name='applications', on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    age = models.IntegerField()
    content = models.TextField()
    education = models.CharField(max_length=100)
    location = models.TextField()
    email = models.EmailField()
    language = models.CharField(max_length=20)

    experience = models.TextField()
    cv_file = models.FileField(upload_to='cv_files/')

    created_by = models.ForeignKey(User, related_name='applications', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

apps/job/views.py
from django.shortcuts import render,redirect , get_object_or_404,HttpResponse
from .models import *
from .form import AddJobForm ,ApplicationForm
from django.contrib.auth.decorators import login_required
from apps.notification.utilities import create_notification


def job_details(request, pk):
    job = Job.objects.get(id=pk)

    return render(request, 'job/jobdetailpage.html', {'job': job})

@login_required
def add_job(request):
    if request.method == 'POST':
        form = AddJobForm(request.POST)
        if form.is_valid():
            job = form.save(commit=False)
            job.created_by = request.user
            job.save()
            return redirect('dashboard')
    else:
        
        form = AddJobForm()
    if request.user.userprofile.is_employer == True:
    
        return render(request, 'job/addjob.html', {'form':form})

@login_required
def apply_for_job(request, pk):
    job = Job.objects.get(id=pk)
    user = request.user

    existing_applications = Application.objects.filter(job=job, created_by=user)
    if existing_applications.exists():
        return HttpResponse("You've already applied for this job.")

    if request.method == 'POST':
        form = ApplicationForm(request.POST, request.FILES)
        if form.is_valid():
            application = form.save(commit=False)
            application.job = job
            application.created_by = user

            if 'cv_file' in request.FILES:
                application.cv_file = request.FILES['cv_file']

            application.save()

            create_notification(request, job.created_by, 'application', extra_id=application.id)

            return redirect('dashboard')
    else:
        form = ApplicationForm()

    return render(request, 'job/apply_for_job.html', {'form': form, 'job': job})

    

def search(request):
    return render(request, 'job/search.html')

@login_required
def edit_job(request, job_id):
    job = get_object_or_404(Job, pk=job_id, created_by=request.user)

    if request.method == 'POST':
        form = AddJobForm(request.POST, instance=job)

        if form.is_valid():
            job = form.save(commit=False)
            job.status = request.POST.get('status')
            job.save()

            return redirect('dashboard')
    else:
        form = AddJobForm(instance=job)
    
    return render(request, 'job/edit_job.html', {'form': form, 'job': job})

apps/job/templates/job/addjob.html
{% extends 'core/base.html' %}

{% block content %}
    <div id="add-job-app" class="my-5">
        <h1 class="display-4 mb-3">Add job</h1>

        <form v-on:submit="validateForm" method="post" action=".">
            {% csrf_token %}

            {% if form.errors %}
                {% for error in form.errors %}
                    <div class="notification is-danger">
                        {{ error }}
                    </div>
                {% endfor %}
            {% endif %}

            <div class="notification is-danger" v-if="errors.length > 0">
                <p v-for="error in errors">
                    [[ error ]]
                </p>
            </div>

            <div class="field">
                <label>Title</label>

                <div class="control">
                    <input class="input" type="text" name="title" id="id_title" v-model="title">
                </div>
            </div>

            <div class="field">
                <label>Short description</label>

                <div class="control">
                    <textarea class="textarea" name="short_description" id="id_short_description" v-model="short_description"></textarea>
                </div>
            </div>

            <div class="field">
                <label>Long description</label>

                <div class="control">
                    <textarea class="textarea" name="long_description" id="id_long_description"></textarea>
                </div>
            </div>

            <div class="field">
                <label>Company name</label>

                <div class="control">
                    <input class="input" type="text" name="company_name" id="id_company_name" v-model="company_name">
                </div>
            </div>

            <div class="field">
                <label>Company address</label>

                <div class="control">
                    <input class="input" type="text" name="company_address" id="id_company_address">
                </div>
            </div>

            <div class="field">
                <label>Company zipcode</label>

                <div class="control">
                    <input class="input" type="text" name="company_zipcode" id="id_company_zipcode">
                </div>
            </div>

            <div class="field">
                <label>Company place</label>

                <div class="control">
                    <input class="input" type="text" name="company_place" id="id_company_place">
                </div>
            </div>

            <div class="field">
                <label>Company country</label>

                <div class="control">
                    <input class="input" type="text" name="company_country" id="id_company_country">
                </div>
            </div>

            <div class="field">
                <label>Company size</label>

                <div class="control">
                    <div class="select">
                        <select name="company_size" v-model="company_size">
                            <option value="">Choose size</option>
                            <option value="size_1-9">1-9</option>
                            <option value="size_10-49">10-49</option>
                            <option value="size_50-99">50-99</option>
                            <option value="size_100">100+</option>
                        </select>
                    </div>
                </div>
            </div>


            

            <div class="field">
                <div class="control">
                    <button class="button is-success" type="submit">Submit</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/vue@3"></script>

<script>
    const AddJobApp = {
        data() {
            return {
                title: '',
                company_name: '',
                short_description: '',
                company_size: '',
                errors: [],
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                this.errors = []

                if (this.title === '') {
                    this.errors.push('The title field is missing!')
                }

                if (this.short_description === '') {
                    this.errors.push('The short description field is missing!')
                }

                if (this.company_name === '') {
                    this.errors.push('The company name field is missing!')
                }

                if (this.company_size === '') {
                    this.errors.push('The company size is missing!')
                }

                if (this.errors.length) {
                    e.preventDefault()

                    return false
                } else {
                    return true
                }
            }
        }
    }

    Vue.createApp(AddJobApp).mount('#add-job-app');
</script>
{% endblock %}

apps/job/templates/job/apply_for_job.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="container my-5">
        <h1 class="title mt-5">Apply for Job - {{ job.title }}</h1>

        {% if user.userprofile.linkedin_sub %}
            <hr>
            <form action="{% url 'refresh_linkedin_data' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="button is-success">
                    Apply with LinkedIn
                </button>
            </form>
            <hr>
        {% endif %}

        <form method="post" action="." enctype="multipart/form-data">
            {% csrf_token %}

            {% if form.errors %}
                <div class="notification is-danger">
                    {% for error in form.errors %}
                        {{ error }}
                    {% endfor %}
                </div>
            {% endif %}

            {% with user_data=request.session.user_data %}
                <div class="field">
                    <label class="label">First Name</label>
                    <div class="control">
                        <input type="text" class="input" name="first_name" id="id_first_name"
                               value="{{ user_data.first_name|default:'' }}">
                    </div>
                </div>

                <div class="field">
                    <label class="label">Last Name</label>
                    <div class="control">
                        <input type="text" class="input" name="last_name" id="id_last_name"
                               value="{{ user_data.last_name|default:'' }}">
                    </div>
                </div>

                <div class="field">
                    <label class="label">Email</label>
                    <div class="control">
                        <input type="email" class="input" name="email" id="email"
                               value="{{ user_data.email|default:'' }}">
                    </div>
                </div>

                <div class="field">
                    <label class="label">Location (Address)</label>
                    <div class="control">
                        <textarea class="textarea" rows="2" name="location"
                                  id="id_location">{{ user_data.location|default:'' }}</textarea>
                    </div>
                </div>

                <div class="field">
                    <label class="label">Language</label>
                    <div class="control">
                        <textarea class="textarea" rows="2" name="language"
                                  id="language">{{ user_data.language|default:'' }}</textarea>
                    </div>
                </div>

                <div class="field">
                    <label class="label">Education (for BS or MS)</label>
                    <div class="control">
                        <input type="text" class="input education" name="education" id="id_education">
                    </div>
                </div>

                <div class="field">
                    <label class="label">Content</label>
                    <div class="control">
                        <textarea class="textarea" name="content" id="id_content" rows="5" cols="50"></textarea>
                    </div>
                </div>

                <div class="field">
                    <label class="label">Age</label>
                    <div class="control">
                        <input type="number" class="input" name="age" id="id_age">
                    </div>
                </div>

                <div class="field">
                    <label class="label">Experience (Min 1 year)</label>
                    <div class="control">
                        <textarea class="textarea" rows="5" name="experience" id="id_experience"></textarea>
                    </div>
                </div>

                <div class="field">
                    <label class="label">CV (Resume)</label>
                    <div class="control">
                        <input type="file" name="cv_file" id="id_cv_file" accept=".pdf">
                    </div>
                </div>

                <p class="my-5 notification is-danger">Be careful, you can apply only once.</p>

                <div class="field mb-5">
                    <div class="control">
                        <button class="button is-success">Submit</button>
                    </div>
                </div>
            {% endwith %}
        </form>
    </div>
{% endblock %}

apps/job/templates/job/edit_job.html
{% extends 'core/base.html' %}

{% block content %}
    <div id="edit-job-app" class="my-5">
        <h1 class="display-4 mb-3">Edit job</h1>

        <form v-on:submit="validateForm" method="post" action=".">
            {% csrf_token %}

            {% if form.errors %}
                {% for error in form.errors %}
                    <div class="notification is-danger">
                        {{ error }}
                    </div>
                {% endfor %}
            {% endif %}

            <div class="notification is-danger" v-if="errors.length">
                <p v-for="error in errors">
                    [[ error ]]
                </p>
            </div>

            <div class="field">
                <label>Title</label>

                <div class="control">
                    <input class="input" type="text" name="title" id="id_title" v-model="title">
                </div>
            </div>

            <div class="field">
                <label>Short description</label>

                <div class="control">
                    <textarea class="textarea" name="short_description" id="id_short_description" v-model="short_description"></textarea>
                </div>
            </div>

            <div class="field">
                <label>Long description</label>

                <div class="control">
                    <textarea class="textarea" name="long_description" id="id_long_description">{% if job.long_description %}{{ job.long_description }}{% endif %}</textarea>
                </div>
            </div>

            <div class="field">
                <label>Company name</label>

                <div class="control">
                    <input class="input" type="text" name="company_name" id="id_company_name" v-model="company_name">
                </div>
            </div>

            <div class="field">
                <label>Company address</label>

                <div class="control">
                    <input class="input" type="text" name="company_address" id="id_company_address" value="{% if job.company_address %}{{ job.company_address }}{% endif %}">
                </div>
            </div>

            <div class="field">
                <label>Company zipcode</label>

                <div class="control">
                    <input class="input" type="text" name="company_zipcode" id="id_company_zipcode" value="{% if job.company_zipcode %}{{ job.company_zipcode }}{% endif %}">
                </div>
            </div>

            <div class="field">
                <label>Company place</label>

                <div class="control">
                    <input class="input" type="text" name="company_place" id="id_company_place" value="{% if job.company_place %}{{ job.company_place }}{% endif %}">
                </div>
            </div>

            <div class="field">
                <label>Company country</label>

                <div class="control">
                    <input class="input" type="text" name="company_country" id="id_company_country" value="{% if job.company_country %}{{ job.company_country }}{% endif %}">
                </div>
            </div>

            <div class="field">
                <label>Company size</label>

                <div class="control">
                    <div class="select">
                        <select name="company_size" v-model="company_size">
                            <option value="">Choose size</option>
                            <option value="size_1-9">1-9</option>
                            <option value="size_10-49">10-49</option>
                            <option value="size_50-99">50-99</option>
                            <option value="size_100">100+</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="field">
                <label>Status</label>

                <div class="control">
                    <div class="select">
                        <select name="status">
                            <option value="active"{% if job.status == 'active' %} selected{% endif %}>Active</option>
                            <option value="employed"{% if job.status == 'employed' %} selected{% endif %}>Employed</option>
                            <option value="archived"{% if job.status == 'archived' %} selected{% endif %}>Archived</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <button class="button is-success form-button" type="submit">Save changes</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/vue@3"></script>

<script>
    const EditJobApp = {
        data() {
            return {
                title: '{{ job.title }}',
                company_name: '{{ job.company_name }}',
                short_description: '{{ job.short_description }}',
                company_size: '{{ job.company_size }}',
                errors: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                this.errors = []

                if (this.title === '') {
                    this.errors.push('The title field is missing!')
                }

                if (this.short_description === '') {
                    this.errors.push('The short description field is missing!')
                }

                if (this.company_name === '') {
                    this.errors.push('The company name field is missing!')
                }

                if (this.company_size === '') {
                    this.errors.push('The company size is missing!')
                }

                if (this.errors.length) {
                    e.preventDefault()

                    return false
                } else {
                    return true
                }
            }
        }
    }

    Vue.createApp(EditJobApp).mount('#edit-job-app');
</script>
<style>
     .form-button {
        background-color: #28a745;
        color: #fff;
        transition: background-color 0.3s ease;
    }

    .form-button:hover {
        background-color: #218838; 
    }
</style>
{% endblock %}

apps/job/templates/job/error.html
{% extends 'core/base.html' %}

{% block content %}
<h1>error</h1><p>{{error_message}}</p>

{% endblock %}

apps/job/templates/job/jobdetailpage.html
{% extends 'core/base.html' %}

{% block content %}
<div class="container my-5">
    <h1 class="display-4 mb-3">Job Details</h1>
    <div class="card">
        <div class="card-body">
            <h1 class="card-title job-title" style="font-size: 2em;">
                {{ job.title }} (<span class="{% if job.status == 'active' %}active-job{% else %}hire-job {% endif %}">{{ job.get_status_display }}</span>)
            </h1>

            <p class="card-text job-short-description my-3" style="font-size: 1.2em;">
                {{ job.short_description }}
            </p>

            <p class="card-text lead job-long-description" style="font-size: 1em;">
                {{ job.long_description }}
            </p>

            <dl class="row mt-3">
                <dt class="col-sm-3">Company name:</dt>
                <dd class="col-sm-9">{{ job.company_name }}</dd>

                {% if job.company_address %}
                <dt class="col-sm-3">Company address:</dt>
                <dd class="col-sm-9">{{ job.company_address }}</dd>
                {% endif %}

                {% if job.company_zipcode %}
                <dt class="col-sm-3">Company zipcode:</dt>
                <dd class="col-sm-9">{{ job.company_zipcode }}</dd>
                {% endif %}

                {% if job.company_place %}
                <dt class="col-sm-3">Company place:</dt>
                <dd class="col-sm-9">{{ job.company_place }}</dd>
                {% endif %}

                {% if job.company_country %}
                <dt class="col-sm-3">Company country:</dt>
                <dd class="col-sm-9">{{ job.company_country }}</dd>
                {% endif %}

                {% if job.get_company_size_display %}
                <dt class="col-sm-3">Company size:</dt>
                <dd class="col-sm-9">{{ job.get_company_size_display }}</dd>
                {% endif %}
            </dl>

            <hr>

            {% if request.user.userprofile.is_employer %}
            <p class="alert alert-info">This job is not available for employers!</p>
            {% elif job.status == 'active' and not request.user.userprofile.is_employer %}
            <a href="{% url 'apply_for_job' job.id %}" class="btn btn-success apply-button">Apply Now</a>
            {% else %}
            <p class="alert alert-warning">This job is not available anymore!</p>
            {% endif %}
        </div>
    </div>
</div>
<style>
    .active-job {
        font-weight: bold;
        color: rgb(79, 147, 79);
    }
    .hire-job {
        font-weight: bold;
        color: rgb(178, 71, 71);
    }
    .apply-button {
        transition: transform 0.2s ease-in-out;
    }

    .apply-button:hover {
        transform: scale(1.05);
    }
</style>
{% endblock %}

apps/job/templates/job/search.html
{% extends 'core/base.html' %}

{% block content %}
<div id="search-app" class="container my-5">
    <h1 class="display-4 mb-3">Search Jobs</h1>

    <form @submit.prevent="performSearch()" class="mb-4">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="query">Job Title</label>
                    <input type="text" name="query" class="form-control" v-model="query" required>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label for="company_size">Company Size</label>
                    <select name="company_size" class="form-control" v-model="company_size">
                        <option value="" selected>All</option>
                        <option value="size_1-9">1-9</option>
                        <option value="size_10-49">10-49</option>
                        <option value="size_50-99">50-99</option>
                        <option value="size_100">100+</option>
                    </select>
                </div>
            </div>

            <div class="col-md-12">
                <button class="btn btn-success btn-block">Search</button>
            </div>
        </div>
    </form>

    <div v-if="jobs.length > 0">
        <hr>

        <div v-for="job in jobs" :key="job.id" class="card mb-3">
            <div class="card-body">
                <p class="card-text">[[ job.title ]]</p>
                <h3 class="card-title">Company: [[ job.company_name ]]</h3>
                <p><a :href="job.url" class="btn btn-primary">View Details</a></p>
            </div>
        </div>
    </div>
    <div v-if="isDataLoaded">
        <p  class="error-message">Not Found</p>
    </div>
</div>

{% endblock %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/vue@3"></script>
<script>
    const app = Vue.createApp({
        data() {
            return {
                query: '',
                company_size: '',
                jobs: [],
                error: false,
                isDataLoaded: false,

            }
        },
        delimiters: ['[[', ']]'],

        methods: {
            performSearch() {
                const data = {
                    'query': this.query,
                    'company_size': this.company_size
                }

                fetch('/jobs/api/search/', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token }}'
                    },
                    body: JSON.stringify(data)
                })
                    .then((response) => response.json())
                    .then((result) => {
                        this.jobs = result.jobs;
                        this.isDataLoaded = this.jobs.length === 0 ? true : false;
                    })
                    .catch((error) => {
                        this.error = error;
                    })
            }
        }
    })

    app.mount('#search-app')
</script>
{% endblock %}